### PR TITLE
Update tests for dune 3.14

### PR DESCRIPTION
**Pull request by emillon**
dune.3.14.0 adds a loc in its output, see ocaml/dune#9851.

This updates the test output and the constraint.

### CODE REVIEW

**Comment by emillon** [comment]
I tried to `grep -v` to be compatible with both old and new dune, but this is tricky because the line is on stderr, but there are (not pretty) alternatives.

**Review by Leonidas-from-XIV — APPROVED** [review]
Looks ok, given 3.8 and 3.14 support the same OCaml this is close enough.

I assume we'll need add the dune 3.14 constraint in `:with-test` dependencies on opam-repository as well?

**Comment by emillon** [comment]
I already updated the constraints for 2.0.0 here: https://github.com/ocaml/opam-repository/pull/25238

**Comment by Leonidas-from-XIV** [comment]
Merging as dune 3.14 has been released.

**Pull request merged**
